# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.source_memory import SourceMemory
from typing import Optional, Set
from typing_extensions import Self

class MentalModelApiResponse(BaseModel):
    """
    Response model for a mental model (auto-consolidated knowledge).
    """ # noqa: E501
    id: StrictStr = Field(description="Unique mental model ID")
    bank_id: StrictStr = Field(description="Bank this mental model belongs to")
    text: StrictStr = Field(description="The consolidated mental model text")
    proof_count: StrictInt = Field(description="Number of facts supporting this mental model")
    history: Optional[List[Dict[str, Any]]] = Field(default=None, description="History of changes to this mental model")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Tags for scoped visibility")
    source_memory_ids: Optional[List[StrictStr]] = Field(default=None, description="IDs of memories that consolidated into this")
    source_memories: Optional[List[SourceMemory]] = Field(default=None, description="Full source memory details (when requested)")
    created_at: Optional[StrictStr] = None
    updated_at: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["id", "bank_id", "text", "proof_count", "history", "tags", "source_memory_ids", "source_memories", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MentalModelApiResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in source_memories (list)
        _items = []
        if self.source_memories:
            for _item_source_memories in self.source_memories:
                if _item_source_memories:
                    _items.append(_item_source_memories.to_dict())
            _dict['source_memories'] = _items
        # set to None if created_at (nullable) is None
        # and model_fields_set contains the field
        if self.created_at is None and "created_at" in self.model_fields_set:
            _dict['created_at'] = None

        # set to None if updated_at (nullable) is None
        # and model_fields_set contains the field
        if self.updated_at is None and "updated_at" in self.model_fields_set:
            _dict['updated_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MentalModelApiResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "bank_id": obj.get("bank_id"),
            "text": obj.get("text"),
            "proof_count": obj.get("proof_count"),
            "history": obj.get("history"),
            "tags": obj.get("tags"),
            "source_memory_ids": obj.get("source_memory_ids"),
            "source_memories": [SourceMemory.from_dict(_item) for _item in obj["source_memories"]] if obj.get("source_memories") is not None else None,
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


