# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from hindsight_client_api.models.reflect_fact import ReflectFact
from hindsight_client_api.models.reflect_llm_call import ReflectLLMCall
from hindsight_client_api.models.reflect_mental_model import ReflectMentalModel
from hindsight_client_api.models.reflect_tool_call import ReflectToolCall
from hindsight_client_api.models.token_usage import TokenUsage
from typing import Optional, Set
from typing_extensions import Self

class ReflectResponse(BaseModel):
    """
    Response model for think endpoint.
    """ # noqa: E501
    text: StrictStr
    based_on: Optional[List[ReflectFact]] = None
    structured_output: Optional[Dict[str, Any]] = None
    usage: Optional[TokenUsage] = None
    tool_calls: Optional[List[ReflectToolCall]] = None
    llm_calls: Optional[List[ReflectLLMCall]] = None
    mental_models: Optional[List[ReflectMentalModel]] = None
    __properties: ClassVar[List[str]] = ["text", "based_on", "structured_output", "usage", "tool_calls", "llm_calls", "mental_models"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ReflectResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in based_on (list)
        _items = []
        if self.based_on:
            for _item_based_on in self.based_on:
                if _item_based_on:
                    _items.append(_item_based_on.to_dict())
            _dict['based_on'] = _items
        # override the default output from pydantic by calling `to_dict()` of usage
        if self.usage:
            _dict['usage'] = self.usage.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in tool_calls (list)
        _items = []
        if self.tool_calls:
            for _item_tool_calls in self.tool_calls:
                if _item_tool_calls:
                    _items.append(_item_tool_calls.to_dict())
            _dict['tool_calls'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in llm_calls (list)
        _items = []
        if self.llm_calls:
            for _item_llm_calls in self.llm_calls:
                if _item_llm_calls:
                    _items.append(_item_llm_calls.to_dict())
            _dict['llm_calls'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in mental_models (list)
        _items = []
        if self.mental_models:
            for _item_mental_models in self.mental_models:
                if _item_mental_models:
                    _items.append(_item_mental_models.to_dict())
            _dict['mental_models'] = _items
        # set to None if structured_output (nullable) is None
        # and model_fields_set contains the field
        if self.structured_output is None and "structured_output" in self.model_fields_set:
            _dict['structured_output'] = None

        # set to None if usage (nullable) is None
        # and model_fields_set contains the field
        if self.usage is None and "usage" in self.model_fields_set:
            _dict['usage'] = None

        # set to None if tool_calls (nullable) is None
        # and model_fields_set contains the field
        if self.tool_calls is None and "tool_calls" in self.model_fields_set:
            _dict['tool_calls'] = None

        # set to None if llm_calls (nullable) is None
        # and model_fields_set contains the field
        if self.llm_calls is None and "llm_calls" in self.model_fields_set:
            _dict['llm_calls'] = None

        # set to None if mental_models (nullable) is None
        # and model_fields_set contains the field
        if self.mental_models is None and "mental_models" in self.model_fields_set:
            _dict['mental_models'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ReflectResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "text": obj.get("text"),
            "based_on": [ReflectFact.from_dict(_item) for _item in obj["based_on"]] if obj.get("based_on") is not None else None,
            "structured_output": obj.get("structured_output"),
            "usage": TokenUsage.from_dict(obj["usage"]) if obj.get("usage") is not None else None,
            "tool_calls": [ReflectToolCall.from_dict(_item) for _item in obj["tool_calls"]] if obj.get("tool_calls") is not None else None,
            "llm_calls": [ReflectLLMCall.from_dict(_item) for _item in obj["llm_calls"]] if obj.get("llm_calls") is not None else None,
            "mental_models": [ReflectMentalModel.from_dict(_item) for _item in obj["mental_models"]] if obj.get("mental_models") is not None else None
        })
        return _obj


