# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.api.operations_api import OperationsApi


class TestOperationsApi(unittest.IsolatedAsyncioTestCase):
    """OperationsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = OperationsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_cancel_operation(self) -> None:
        """Test case for cancel_operation

        Cancel a pending async operation
        """
        pass

    async def test_list_operations(self) -> None:
        """Test case for list_operations

        List async operations
        """
        pass


if __name__ == '__main__':
    unittest.main()
