# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.api.entities_api import EntitiesApi


class TestEntitiesApi(unittest.IsolatedAsyncioTestCase):
    """EntitiesApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = EntitiesApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_get_entity(self) -> None:
        """Test case for get_entity

        Get entity details
        """
        pass

    async def test_list_entities(self) -> None:
        """Test case for list_entities

        List entities
        """
        pass

    async def test_regenerate_entity_observations(self) -> None:
        """Test case for regenerate_entity_observations

        Regenerate entity observations
        """
        pass


if __name__ == '__main__':
    unittest.main()
