# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.api.documents_api import DocumentsApi


class TestDocumentsApi(unittest.IsolatedAsyncioTestCase):
    """DocumentsApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = DocumentsApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_delete_document(self) -> None:
        """Test case for delete_document

        Delete a document
        """
        pass

    async def test_get_chunk(self) -> None:
        """Test case for get_chunk

        Get chunk details
        """
        pass

    async def test_get_document(self) -> None:
        """Test case for get_document

        Get document details
        """
        pass

    async def test_list_documents(self) -> None:
        """Test case for list_documents

        List documents
        """
        pass


if __name__ == '__main__':
    unittest.main()
