# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.api.memory_api import MemoryApi


class TestMemoryApi(unittest.IsolatedAsyncioTestCase):
    """MemoryApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = MemoryApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_clear_bank_memories(self) -> None:
        """Test case for clear_bank_memories

        Clear memory bank memories
        """
        pass

    async def test_get_graph(self) -> None:
        """Test case for get_graph

        Get memory graph data
        """
        pass

    async def test_list_memories(self) -> None:
        """Test case for list_memories

        List memory units
        """
        pass

    async def test_recall_memories(self) -> None:
        """Test case for recall_memories

        Recall memory
        """
        pass

    async def test_reflect(self) -> None:
        """Test case for reflect

        Reflect and generate answer
        """
        pass

    async def test_retain_memories(self) -> None:
        """Test case for retain_memories

        Retain memories
        """
        pass


if __name__ == '__main__':
    unittest.main()
