# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.operations_list_response import OperationsListResponse

class TestOperationsListResponse(unittest.TestCase):
    """OperationsListResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperationsListResponse:
        """Test OperationsListResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperationsListResponse`
        """
        model = OperationsListResponse()
        if include_optional:
            return OperationsListResponse(
                bank_id = '',
                operations = [
                    {created_at=2024-01-15T10:30:00Z, document_id=meeting-notes-2024, id=550e8400-e29b-41d4-a716-446655440000, items_count=5, status=pending, task_type=retain}
                    ]
            )
        else:
            return OperationsListResponse(
                bank_id = '',
                operations = [
                    {created_at=2024-01-15T10:30:00Z, document_id=meeting-notes-2024, id=550e8400-e29b-41d4-a716-446655440000, items_count=5, status=pending, task_type=retain}
                    ],
        )
        """

    def testOperationsListResponse(self):
        """Test OperationsListResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
