# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.api.banks_api import BanksApi


class TestBanksApi(unittest.IsolatedAsyncioTestCase):
    """BanksApi unit test stubs"""

    async def asyncSetUp(self) -> None:
        self.api = BanksApi()

    async def asyncTearDown(self) -> None:
        await self.api.api_client.close()

    async def test_add_bank_background(self) -> None:
        """Test case for add_bank_background

        Add/merge memory bank background
        """
        pass

    async def test_create_or_update_bank(self) -> None:
        """Test case for create_or_update_bank

        Create or update memory bank
        """
        pass

    async def test_delete_bank(self) -> None:
        """Test case for delete_bank

        Delete memory bank
        """
        pass

    async def test_get_agent_stats(self) -> None:
        """Test case for get_agent_stats

        Get statistics for memory bank
        """
        pass

    async def test_get_bank_profile(self) -> None:
        """Test case for get_bank_profile

        Get memory bank profile
        """
        pass

    async def test_list_banks(self) -> None:
        """Test case for list_banks

        List all memory banks
        """
        pass

    async def test_update_bank_disposition(self) -> None:
        """Test case for update_bank_disposition

        Update memory bank disposition
        """
        pass


if __name__ == '__main__':
    unittest.main()
