# coding: utf-8

"""
    Hindsight HTTP API

    HTTP API for Hindsight

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from hindsight_client_api.models.operation_response import OperationResponse

class TestOperationResponse(unittest.TestCase):
    """OperationResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> OperationResponse:
        """Test OperationResponse
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `OperationResponse`
        """
        model = OperationResponse()
        if include_optional:
            return OperationResponse(
                id = '',
                task_type = '',
                items_count = 56,
                document_id = '',
                created_at = '',
                status = '',
                error_message = ''
            )
        else:
            return OperationResponse(
                id = '',
                task_type = '',
                items_count = 56,
                document_id = '',
                created_at = '',
                status = '',
                error_message = '',
        )
        """

    def testOperationResponse(self):
        """Test OperationResponse"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
